var res = {
    Plankton_png : "res/Sprites/plankton.png",
    underwater_png : "res/Background/underwater_new.png",
    CloseNormal_png : "res/CloseNormal.png",
    CloseSelected_png : "res/CloseSelected.png",
    bubbles1_png : "res/Foreground/bubbles1.png",
    bubbles2_png : "res/Foreground/bubbles2.png",
    coral1_png : "res/Foreground/coral1.png",
    coral2_png : "res/Foreground/coral2.png",
    weed_png : "res/Foreground/weed.png",
    weed2_png : "res/Foreground/weed2.png",
    weed3_png : "res/Foreground/weed3.png",
    jellyfish1_png : "res/Sprites/jellyfish1.png",
    jellyfish2_png : "res/Sprites/jellyfish2.png",
    rock1_png : "res/Sprites/rock1.png",
    rock2_png : "res/Sprites/rock2.png",
    rock3_png : "res/Sprites/rock3.png",
    BatteryStage1_png : "res/HUD/BatteryStage1.png",
    BatteryStage2_png : "res/HUD/BatteryStage2.png",
    BatteryStage3_png : "res/HUD/BatteryStage3.png",
    CameraHud1_png : "res/HUD/CameraHud1.png",
    CameraHud2_png : "res/HUD/CameraHud2.png",
    startButtonNormal: "res/start_normal.png",
    startButtonSelect: "res/start_selected.png",
    whale_png: "res/Sprites/munch.png",
    whale_plist: "res/Sprites/munch.plist",
    restartButtonNormal: "res/restart_n.png",
    restartButtonSelect: "res/restart_s.png",
    jellyfish_plist: "res/Sprites/float.plist",
    jellyfish_png: "res/Sprites/float.png",
    shrimp_plist: "res/Sprites/swim.plist",
    shrimp_png: "res/Sprites/swim.png",
    collectible_png: "res/Sprites/collectible.png",
    music_mp3: "res/Sounds/another_chasing_theme_maybe.mp3",
    collectible_mp3: "res/Sounds/collectible.mp3",
    gameOver_mp3: "res/Sounds/game_over.wav",
    op1_png: "res/op1.png",
    op2_png: "res/op2.png",
    op3_png: "res/op3.png",
    end_png: "res/end.png",
    button_mp3: "res/Sounds/pause_resume_button_sound.wav"
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}